# 💝 طرق دعم المشروع | Project Funding

# هذا الملف يُستخدم من قبل GitHub لعرض زر "Sponsor" في الصفحة الرئيسية للمشروع
# This file is used by GitHub to display the "Sponsor" button on the project page

# GitHub Sponsors
github: [azadsystems]

# Patreon
patreon: azadsystems

# Open Collective
open_collective: azadsystems

# Ko-fi
ko_fi: azadsystems

# Buy Me a Coffee
custom: ["https://buymeacoffee.com/azadsystems", "https://azad-systems.com/donate"]

