"""add_fx_rates_to_checks

Revision ID: 0b2b07b6d221
Revises: 7f493772189f
Create Date: 2025-10-21 10:46:50.713439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b2b07b6d221'
down_revision = '7f493772189f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fx_rate_issue', sa.Numeric(precision=10, scale=6), nullable=True))
        batch_op.add_column(sa.Column('fx_rate_issue_source', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('fx_rate_issue_timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('fx_rate_issue_base', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('fx_rate_issue_quote', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('fx_rate_cash', sa.Numeric(precision=10, scale=6), nullable=True))
        batch_op.add_column(sa.Column('fx_rate_cash_source', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('fx_rate_cash_timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('fx_rate_cash_base', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('fx_rate_cash_quote', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checks', schema=None) as batch_op:
        batch_op.drop_column('fx_rate_cash_quote')
        batch_op.drop_column('fx_rate_cash_base')
        batch_op.drop_column('fx_rate_cash_timestamp')
        batch_op.drop_column('fx_rate_cash_source')
        batch_op.drop_column('fx_rate_cash')
        batch_op.drop_column('fx_rate_issue_quote')
        batch_op.drop_column('fx_rate_issue_base')
        batch_op.drop_column('fx_rate_issue_timestamp')
        batch_op.drop_column('fx_rate_issue_source')
        batch_op.drop_column('fx_rate_issue')

    # ### end Alembic commands ###
