"""Add archives table

Revision ID: 0efbfee91f13
Revises: b2350ce538a9
Create Date: 2025-10-13 22:12:18.620803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0efbfee91f13'
down_revision = 'b2350ce538a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_type', sa.String(length=50), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('archived_data', sa.Text(), nullable=False),
    sa.Column('archive_reason', sa.String(length=200), nullable=True),
    sa.Column('archived_by', sa.Integer(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=False),
    sa.Column('original_created_at', sa.DateTime(), nullable=True),
    sa.Column('original_updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['archived_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('archives', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_archives_record_id'), ['record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_archives_record_type'), ['record_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archives', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_archives_record_type'))
        batch_op.drop_index(batch_op.f('ix_archives_record_id'))

    op.drop_table('archives')
    # ### end Alembic commands ###
