"""Add avatar_url to User model

Revision ID: 507f88f3971f
Revises: 882fd1716dcf
Create Date: 2025-10-05 09:18:55.142270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '507f88f3971f'
down_revision = '882fd1716dcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar_url')

    # ### end Alembic commands ###
