"""add payment_method to preorders

Revision ID: 51950a3617a6
Revises: 22428e07f512
Create Date: 2025-08-24 21:29:24.802849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51950a3617a6'
down_revision = '22428e07f512'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preorders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=20), server_default='cash', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preorders', schema=None) as batch_op:
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
