"""Add fx_rate fields to all financial models

Revision ID: 7f493772189f
Revises: ee404aa99146
Create Date: 2025-10-21 10:17:13.542432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f493772189f'
down_revision = 'ee404aa99146'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('online_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fx_rate_used', sa.Numeric(precision=10, scale=6), nullable=True))
        batch_op.add_column(sa.Column('fx_rate_source', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('fx_rate_timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('fx_base_currency', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('fx_quote_currency', sa.String(length=10), nullable=True))

    with op.batch_alter_table('online_preorders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('fx_rate_used', sa.Numeric(precision=10, scale=6), nullable=True))
        batch_op.add_column(sa.Column('fx_rate_source', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('fx_rate_timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('fx_base_currency', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('fx_quote_currency', sa.String(length=10), nullable=True))

    with op.batch_alter_table('partner_settlements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fx_rate_used', sa.Numeric(precision=10, scale=6), nullable=True))
        batch_op.add_column(sa.Column('fx_rate_source', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('fx_rate_timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('fx_base_currency', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('fx_quote_currency', sa.String(length=10), nullable=True))

    with op.batch_alter_table('preorders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fx_rate_used', sa.Numeric(precision=10, scale=6), nullable=True))
        batch_op.add_column(sa.Column('fx_rate_source', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('fx_rate_timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('fx_base_currency', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('fx_quote_currency', sa.String(length=10), nullable=True))

    with op.batch_alter_table('sale_returns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fx_rate_used', sa.Numeric(precision=10, scale=6), nullable=True))
        batch_op.add_column(sa.Column('fx_rate_source', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('fx_rate_timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('fx_base_currency', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('fx_quote_currency', sa.String(length=10), nullable=True))

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fx_rate_used', sa.Numeric(precision=10, scale=6), nullable=True))
        batch_op.add_column(sa.Column('fx_rate_source', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('fx_rate_timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('fx_base_currency', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('fx_quote_currency', sa.String(length=10), nullable=True))

    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fx_rate_used', sa.Numeric(precision=10, scale=6), nullable=True))
        batch_op.add_column(sa.Column('fx_rate_source', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('fx_rate_timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('fx_base_currency', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('fx_quote_currency', sa.String(length=10), nullable=True))

    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fx_rate_used', sa.Numeric(precision=10, scale=6), nullable=True))
        batch_op.add_column(sa.Column('fx_rate_source', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('fx_rate_timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('fx_base_currency', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('fx_quote_currency', sa.String(length=10), nullable=True))

    with op.batch_alter_table('supplier_settlements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fx_rate_used', sa.Numeric(precision=10, scale=6), nullable=True))
        batch_op.add_column(sa.Column('fx_rate_source', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('fx_rate_timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('fx_base_currency', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('fx_quote_currency', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier_settlements', schema=None) as batch_op:
        batch_op.drop_column('fx_quote_currency')
        batch_op.drop_column('fx_base_currency')
        batch_op.drop_column('fx_rate_timestamp')
        batch_op.drop_column('fx_rate_source')
        batch_op.drop_column('fx_rate_used')

    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.drop_column('fx_quote_currency')
        batch_op.drop_column('fx_base_currency')
        batch_op.drop_column('fx_rate_timestamp')
        batch_op.drop_column('fx_rate_source')
        batch_op.drop_column('fx_rate_used')

    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.drop_column('fx_quote_currency')
        batch_op.drop_column('fx_base_currency')
        batch_op.drop_column('fx_rate_timestamp')
        batch_op.drop_column('fx_rate_source')
        batch_op.drop_column('fx_rate_used')

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_column('fx_quote_currency')
        batch_op.drop_column('fx_base_currency')
        batch_op.drop_column('fx_rate_timestamp')
        batch_op.drop_column('fx_rate_source')
        batch_op.drop_column('fx_rate_used')

    with op.batch_alter_table('sale_returns', schema=None) as batch_op:
        batch_op.drop_column('fx_quote_currency')
        batch_op.drop_column('fx_base_currency')
        batch_op.drop_column('fx_rate_timestamp')
        batch_op.drop_column('fx_rate_source')
        batch_op.drop_column('fx_rate_used')

    with op.batch_alter_table('preorders', schema=None) as batch_op:
        batch_op.drop_column('fx_quote_currency')
        batch_op.drop_column('fx_base_currency')
        batch_op.drop_column('fx_rate_timestamp')
        batch_op.drop_column('fx_rate_source')
        batch_op.drop_column('fx_rate_used')

    with op.batch_alter_table('partner_settlements', schema=None) as batch_op:
        batch_op.drop_column('fx_quote_currency')
        batch_op.drop_column('fx_base_currency')
        batch_op.drop_column('fx_rate_timestamp')
        batch_op.drop_column('fx_rate_source')
        batch_op.drop_column('fx_rate_used')

    with op.batch_alter_table('online_preorders', schema=None) as batch_op:
        batch_op.drop_column('fx_quote_currency')
        batch_op.drop_column('fx_base_currency')
        batch_op.drop_column('fx_rate_timestamp')
        batch_op.drop_column('fx_rate_source')
        batch_op.drop_column('fx_rate_used')
        batch_op.drop_column('currency')

    with op.batch_alter_table('online_payments', schema=None) as batch_op:
        batch_op.drop_column('fx_quote_currency')
        batch_op.drop_column('fx_base_currency')
        batch_op.drop_column('fx_rate_timestamp')
        batch_op.drop_column('fx_rate_source')
        batch_op.drop_column('fx_rate_used')

    # ### end Alembic commands ###
