"""Add hard delete system with DeletionLog model

Revision ID: 882fd1716dcf
Revises: bb72a9ac49f4
Create Date: 2025-10-05 03:13:19.014595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '882fd1716dcf'
down_revision = 'bb72a9ac49f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deletion_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deletion_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('entity_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_by', sa.Integer(), nullable=False),
    sa.Column('deletion_reason', sa.Text(), nullable=True),
    sa.Column('confirmation_code', sa.String(length=50), nullable=True),
    sa.Column('deleted_data', sa.JSON(), nullable=True),
    sa.Column('related_entities', sa.JSON(), nullable=True),
    sa.Column('stock_reversals', sa.JSON(), nullable=True),
    sa.Column('accounting_reversals', sa.JSON(), nullable=True),
    sa.Column('balance_reversals', sa.JSON(), nullable=True),
    sa.Column('restored_at', sa.DateTime(), nullable=True),
    sa.Column('restored_by', sa.Integer(), nullable=True),
    sa.Column('restoration_notes', sa.Text(), nullable=True),
    sa.CheckConstraint('status IN ("PENDING","COMPLETED","FAILED","RESTORED")', name='chk_deletion_status'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['restored_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deletion_logs', schema=None) as batch_op:
        batch_op.create_index('ix_deletion_entity', ['deletion_type', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deletion_logs_confirmation_code'), ['confirmation_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_deletion_logs_deleted_by'), ['deleted_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_deletion_logs_deletion_type'), ['deletion_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_deletion_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deletion_logs_status'), ['status'], unique=False)
        batch_op.create_index('ix_deletion_type_status', ['deletion_type', 'status'], unique=False)

    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivered_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.Numeric(precision=10, scale=3), nullable=True))
        batch_op.add_column(sa.Column('dimensions', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('package_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('delivery_method', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('delivery_instructions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('customs_declaration', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('customs_cleared_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('delivery_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_delivery_attempt', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('return_reason', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.drop_column('return_reason')
        batch_op.drop_column('last_delivery_attempt')
        batch_op.drop_column('delivery_attempts')
        batch_op.drop_column('customs_cleared_date')
        batch_op.drop_column('customs_declaration')
        batch_op.drop_column('delivery_instructions')
        batch_op.drop_column('delivery_method')
        batch_op.drop_column('priority')
        batch_op.drop_column('package_count')
        batch_op.drop_column('dimensions')
        batch_op.drop_column('weight')
        batch_op.drop_column('total_cost')
        batch_op.drop_column('delivered_date')

    with op.batch_alter_table('deletion_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_deletion_type_status')
        batch_op.drop_index(batch_op.f('ix_deletion_logs_status'))
        batch_op.drop_index(batch_op.f('ix_deletion_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_deletion_logs_deletion_type'))
        batch_op.drop_index(batch_op.f('ix_deletion_logs_deleted_by'))
        batch_op.drop_index(batch_op.f('ix_deletion_logs_confirmation_code'))
        batch_op.drop_index('ix_deletion_entity')

    op.drop_table('deletion_logs')
    # ### end Alembic commands ###
