from alembic import op
import sqlalchemy as sa


revision = '9e5608f9b2b0'
down_revision = '20251111_expense_extended_fields'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('expenses') as batch:
        batch.add_column(sa.Column('rent_property_address', sa.String(length=200), nullable=True))
        batch.add_column(sa.Column('rent_property_notes', sa.Text(), nullable=True))
        batch.add_column(sa.Column('tech_provider_name', sa.String(length=200), nullable=True))
        batch.add_column(sa.Column('tech_provider_phone', sa.String(length=30), nullable=True))
        batch.add_column(sa.Column('tech_provider_address', sa.String(length=200), nullable=True))
        batch.add_column(sa.Column('tech_subscription_id', sa.String(length=100), nullable=True))
        batch.add_column(sa.Column('storage_property_address', sa.String(length=200), nullable=True))
        batch.add_column(sa.Column('storage_expected_days', sa.Integer(), nullable=True))
        batch.add_column(sa.Column('storage_start_date', sa.Date(), nullable=True))
        batch.add_column(sa.Column('storage_notes', sa.Text(), nullable=True))
        batch.add_column(sa.Column('customs_arrival_date', sa.Date(), nullable=True))
        batch.add_column(sa.Column('customs_departure_date', sa.Date(), nullable=True))
        batch.add_column(sa.Column('customs_origin', sa.String(length=200), nullable=True))
        batch.add_column(sa.Column('customs_port_name', sa.String(length=200), nullable=True))
        batch.add_column(sa.Column('customs_notes', sa.Text(), nullable=True))
        batch.add_column(sa.Column('training_company_name', sa.String(length=200), nullable=True))
        batch.add_column(sa.Column('training_location', sa.String(length=200), nullable=True))
        batch.add_column(sa.Column('training_duration_days', sa.Integer(), nullable=True))
        batch.add_column(sa.Column('training_participants_count', sa.Integer(), nullable=True))
        batch.add_column(sa.Column('training_notes', sa.Text(), nullable=True))
        batch.add_column(sa.Column('training_participants_names', sa.Text(), nullable=True))
        batch.add_column(sa.Column('training_topics', sa.Text(), nullable=True))
        batch.add_column(sa.Column('entertainment_duration_days', sa.Integer(), nullable=True))
        batch.add_column(sa.Column('entertainment_notes', sa.Text(), nullable=True))
        batch.add_column(sa.Column('bank_fee_reference', sa.String(length=100), nullable=True))
        batch.add_column(sa.Column('bank_fee_contact_name', sa.String(length=200), nullable=True))
        batch.add_column(sa.Column('bank_fee_contact_phone', sa.String(length=30), nullable=True))
        batch.add_column(sa.Column('gov_fee_reference', sa.String(length=100), nullable=True))
        batch.add_column(sa.Column('port_fee_reference', sa.String(length=100), nullable=True))
        batch.add_column(sa.Column('port_fee_agent_name', sa.String(length=200), nullable=True))
        batch.add_column(sa.Column('port_fee_agent_phone', sa.String(length=30), nullable=True))
        batch.add_column(sa.Column('salary_notes', sa.Text(), nullable=True))
        batch.add_column(sa.Column('salary_reference', sa.String(length=100), nullable=True))
        batch.add_column(sa.Column('travel_duration_days', sa.Integer(), nullable=True))
        batch.add_column(sa.Column('travel_start_date', sa.Date(), nullable=True))
        batch.add_column(sa.Column('travel_companions', sa.Text(), nullable=True))
        batch.add_column(sa.Column('travel_cost_center', sa.String(length=100), nullable=True))
        batch.add_column(sa.Column('employee_advance_period', sa.String(length=100), nullable=True))
        batch.add_column(sa.Column('employee_advance_reason', sa.String(length=200), nullable=True))
        batch.add_column(sa.Column('employee_advance_notes', sa.Text(), nullable=True))
        batch.add_column(sa.Column('shipping_date', sa.Date(), nullable=True))
        batch.add_column(sa.Column('shipping_reference', sa.String(length=100), nullable=True))
        batch.add_column(sa.Column('shipping_mode', sa.String(length=50), nullable=True))
        batch.add_column(sa.Column('shipping_tracking_number', sa.String(length=100), nullable=True))
        batch.add_column(sa.Column('maintenance_details', sa.Text(), nullable=True))
        batch.add_column(sa.Column('maintenance_completion_date', sa.Date(), nullable=True))
        batch.add_column(sa.Column('maintenance_technician_name', sa.String(length=200), nullable=True))
        batch.add_column(sa.Column('import_tax_reference', sa.String(length=100), nullable=True))
        batch.add_column(sa.Column('import_tax_notes', sa.Text(), nullable=True))
        batch.add_column(sa.Column('hospitality_type', sa.String(length=20), nullable=True))
        batch.add_column(sa.Column('hospitality_notes', sa.Text(), nullable=True))
        batch.add_column(sa.Column('hospitality_attendees', sa.Text(), nullable=True))
        batch.add_column(sa.Column('hospitality_location', sa.String(length=200), nullable=True))
        batch.add_column(sa.Column('telecom_notes', sa.Text(), nullable=True))
        batch.add_column(sa.Column('office_supplier_name', sa.String(length=200), nullable=True))
        batch.add_column(sa.Column('office_notes', sa.Text(), nullable=True))
        batch.add_column(sa.Column('office_items_list', sa.Text(), nullable=True))
        batch.add_column(sa.Column('office_purchase_reference', sa.String(length=100), nullable=True))
        batch.add_column(sa.Column('home_relation_to_company', sa.String(length=100), nullable=True))
        batch.add_column(sa.Column('home_address', sa.String(length=200), nullable=True))
        batch.add_column(sa.Column('home_owner_name', sa.String(length=200), nullable=True))
        batch.add_column(sa.Column('home_notes', sa.Text(), nullable=True))
        batch.add_column(sa.Column('home_cost_share', sa.Numeric(12, 2), nullable=True))
        batch.add_column(sa.Column('partner_expense_reason', sa.String(length=200), nullable=True))
        batch.add_column(sa.Column('partner_expense_notes', sa.Text(), nullable=True))
        batch.add_column(sa.Column('partner_expense_reference', sa.String(length=100), nullable=True))
        batch.add_column(sa.Column('supplier_expense_reason', sa.String(length=200), nullable=True))
        batch.add_column(sa.Column('supplier_expense_notes', sa.Text(), nullable=True))
        batch.add_column(sa.Column('supplier_expense_reference', sa.String(length=100), nullable=True))
        batch.add_column(sa.Column('handling_notes', sa.Text(), nullable=True))
        batch.add_column(sa.Column('handling_quantity', sa.Numeric(12, 2), nullable=True))
        batch.add_column(sa.Column('handling_unit', sa.String(length=50), nullable=True))
        batch.add_column(sa.Column('handling_reference', sa.String(length=100), nullable=True))
        batch.add_column(sa.Column('fuel_vehicle_number', sa.String(length=50), nullable=True))
        batch.add_column(sa.Column('fuel_driver_name', sa.String(length=100), nullable=True))
        batch.add_column(sa.Column('fuel_usage_type', sa.String(length=20), nullable=True))
        batch.add_column(sa.Column('fuel_volume', sa.Numeric(12, 3), nullable=True))
        batch.add_column(sa.Column('fuel_notes', sa.Text(), nullable=True))
        batch.add_column(sa.Column('fuel_station_name', sa.String(length=200), nullable=True))
        batch.add_column(sa.Column('fuel_odometer_start', sa.Integer(), nullable=True))
        batch.add_column(sa.Column('fuel_odometer_end', sa.Integer(), nullable=True))
        batch.add_column(sa.Column('transport_beneficiary_name', sa.String(length=200), nullable=True))
        batch.add_column(sa.Column('transport_reason', sa.String(length=200), nullable=True))
        batch.add_column(sa.Column('transport_usage_type', sa.String(length=20), nullable=True))
        batch.add_column(sa.Column('transport_notes', sa.Text(), nullable=True))
        batch.add_column(sa.Column('transport_route_details', sa.Text(), nullable=True))
        batch.add_column(sa.Column('insurance_policy_number', sa.String(length=100), nullable=True))
        batch.add_column(sa.Column('insurance_notes', sa.Text(), nullable=True))
        batch.add_column(sa.Column('legal_company_name', sa.String(length=200), nullable=True))
        batch.add_column(sa.Column('legal_company_address', sa.String(length=200), nullable=True))
        batch.add_column(sa.Column('legal_case_notes', sa.Text(), nullable=True))
        batch.add_column(sa.Column('legal_case_number', sa.String(length=100), nullable=True))
        batch.add_column(sa.Column('legal_case_type', sa.String(length=100), nullable=True))
def downgrade():
    with op.batch_alter_table('expenses') as batch:
        batch.drop_column('legal_case_type')
        batch.drop_column('legal_case_number')
        batch.drop_column('legal_case_notes')
        batch.drop_column('legal_company_address')
        batch.drop_column('legal_company_name')
        batch.drop_column('insurance_notes')
        batch.drop_column('insurance_policy_number')
        batch.drop_column('transport_route_details')
        batch.drop_column('transport_notes')
        batch.drop_column('transport_usage_type')
        batch.drop_column('transport_reason')
        batch.drop_column('transport_beneficiary_name')
        batch.drop_column('fuel_odometer_end')
        batch.drop_column('fuel_odometer_start')
        batch.drop_column('fuel_station_name')
        batch.drop_column('fuel_notes')
        batch.drop_column('fuel_volume')
        batch.drop_column('fuel_usage_type')
        batch.drop_column('fuel_driver_name')
        batch.drop_column('fuel_vehicle_number')
        batch.drop_column('handling_reference')
        batch.drop_column('handling_unit')
        batch.drop_column('handling_quantity')
        batch.drop_column('handling_notes')
        batch.drop_column('supplier_expense_reference')
        batch.drop_column('supplier_expense_notes')
        batch.drop_column('supplier_expense_reason')
        batch.drop_column('partner_expense_reference')
        batch.drop_column('partner_expense_notes')
        batch.drop_column('partner_expense_reason')
        batch.drop_column('home_cost_share')
        batch.drop_column('home_notes')
        batch.drop_column('home_owner_name')
        batch.drop_column('home_address')
        batch.drop_column('home_relation_to_company')
        batch.drop_column('office_purchase_reference')
        batch.drop_column('office_items_list')
        batch.drop_column('office_notes')
        batch.drop_column('office_supplier_name')
        batch.drop_column('telecom_notes')
        batch.drop_column('hospitality_location')
        batch.drop_column('hospitality_attendees')
        batch.drop_column('hospitality_notes')
        batch.drop_column('hospitality_type')
        batch.drop_column('import_tax_notes')
        batch.drop_column('import_tax_reference')
        batch.drop_column('maintenance_technician_name')
        batch.drop_column('maintenance_completion_date')
        batch.drop_column('maintenance_details')
        batch.drop_column('shipping_tracking_number')
        batch.drop_column('shipping_mode')
        batch.drop_column('shipping_reference')
        batch.drop_column('shipping_date')
        batch.drop_column('employee_advance_notes')
        batch.drop_column('employee_advance_reason')
        batch.drop_column('employee_advance_period')
        batch.drop_column('travel_cost_center')
        batch.drop_column('travel_companions')
        batch.drop_column('travel_start_date')
        batch.drop_column('travel_duration_days')
        batch.drop_column('salary_reference')
        batch.drop_column('salary_notes')
        batch.drop_column('port_fee_agent_phone')
        batch.drop_column('port_fee_agent_name')
        batch.drop_column('port_fee_reference')
        batch.drop_column('gov_fee_reference')
        batch.drop_column('bank_fee_contact_phone')
        batch.drop_column('bank_fee_contact_name')
        batch.drop_column('bank_fee_reference')
        batch.drop_column('entertainment_notes')
        batch.drop_column('entertainment_duration_days')
        batch.drop_column('training_topics')
        batch.drop_column('training_participants_names')
        batch.drop_column('training_notes')
        batch.drop_column('training_participants_count')
        batch.drop_column('training_duration_days')
        batch.drop_column('training_location')
        batch.drop_column('training_company_name')
        batch.drop_column('customs_notes')
        batch.drop_column('customs_port_name')
        batch.drop_column('customs_origin')
        batch.drop_column('customs_departure_date')
        batch.drop_column('customs_arrival_date')
        batch.drop_column('storage_notes')
        batch.drop_column('storage_start_date')
        batch.drop_column('storage_expected_days')
        batch.drop_column('storage_property_address')
        batch.drop_column('tech_subscription_id')
        batch.drop_column('tech_provider_address')
        batch.drop_column('tech_provider_phone')
        batch.drop_column('tech_provider_name')
        batch.drop_column('rent_property_notes')
        batch.drop_column('rent_property_address')
