"""add target and notification fields to notes

Revision ID: b2350ce538a9
Revises: b99c26a60fac
Create Date: 2025-10-06 02:44:10.533362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2350ce538a9'
down_revision = 'b99c26a60fac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('target_ids', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('notification_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('notification_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_sent', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.create_index(batch_op.f('ix_notes_is_sent'), ['is_sent'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_notification_date'), ['notification_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_notification_type'), ['notification_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_target_type'), ['target_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_target_type'))
        batch_op.drop_index(batch_op.f('ix_notes_notification_type'))
        batch_op.drop_index(batch_op.f('ix_notes_notification_date'))
        batch_op.drop_index(batch_op.f('ix_notes_is_sent'))
        batch_op.drop_column('is_sent')
        batch_op.drop_column('notification_date')
        batch_op.drop_column('notification_type')
        batch_op.drop_column('target_ids')
        batch_op.drop_column('target_type')

    # ### end Alembic commands ###
