"""add fx rate fields to payments

Revision ID: b99c26a60fac
Revises: 41d8fc65fb2b
Create Date: 2025-10-06 00:32:32.958480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b99c26a60fac'
down_revision = '41d8fc65fb2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fx_rate_used', sa.Numeric(precision=10, scale=6), nullable=True))
        batch_op.add_column(sa.Column('fx_rate_source', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('fx_rate_timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('fx_base_currency', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('fx_quote_currency', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('fx_quote_currency')
        batch_op.drop_column('fx_base_currency')
        batch_op.drop_column('fx_rate_timestamp')
        batch_op.drop_column('fx_rate_source')
        batch_op.drop_column('fx_rate_used')

    # ### end Alembic commands ###
