"""add warehouse_id to products

Revision ID: d0ea84569208
Revises: 48166b6e9491
Create Date: 2025-07-31 18:33:05.786606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0ea84569208'
down_revision = '48166b6e9491'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warehouse_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_products_warehouse_id',    # named constraint
            'warehouses',
            ['warehouse_id'], ['id']
        )

    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destination_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_shipments_destination_id',  # named constraint
            'warehouses',
            ['destination_id'], ['id']
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_shipments_destination_id', type_='foreignkey')
        batch_op.drop_column('destination_id')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('fk_products_warehouse_id', type_='foreignkey')
        batch_op.drop_column('warehouse_id')
    # ### end Alembic commands ###
